include ../../common.mk

url-rewrite-spa: ## Test Edge function for URL rewrite SPA
	go test -v -timeout 30m ./... -run ^TestUrlRewriteSpa$
.PHONY: url-rewrite-spa

kvs-jwt-verify: ## Test Edge function for KVS JWT verify
	go test -v -timeout 30m ./... -run ^TestKvsJwtVerify$
.PHONY: kvs-jwt-verify

multi-zone-acm-pub-cert: ## Test Multi Zone ACM Public Certificate
	go test -v -timeout 30m ./... -run ^TestMultiZoneAcmPubCert$
.PHONY: multi-zone-acm-pub-cert
