// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import type { cloudwatchEventTarget } from '@cdktf/provider-aws';
import type { FileProvisioner, IResolvable, ITerraformDependable, ITerraformIterator, LocalExecProvisioner, RemoteExecProvisioner, SSHProvisionerConnection, TerraformCount, TerraformResourceLifecycle, WinrmProvisionerConnection } from 'cdktf';

/**
 * Provides an EventBridge Target resource.
 */
export interface TfTargetConfig {
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/cloudwatch_event_target#target_id CloudwatchEventTarget#target_id}.
   * @stability stable
   */
  readonly targetId?: string;
  /**
   * sqs_target block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/cloudwatch_event_target#sqs_target CloudwatchEventTarget#sqs_target}
   * @stability stable
   */
  readonly sqsTarget?: cloudwatchEventTarget.CloudwatchEventTargetSqsTarget;
  /**
   * sagemaker_pipeline_target block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/cloudwatch_event_target#sagemaker_pipeline_target CloudwatchEventTarget#sagemaker_pipeline_target}
   * @stability stable
   */
  readonly sagemakerPipelineTarget?: cloudwatchEventTarget.CloudwatchEventTargetSagemakerPipelineTarget;
  /**
   * run_command_targets block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/cloudwatch_event_target#run_command_targets CloudwatchEventTarget#run_command_targets}
   * @stability stable
   */
  readonly runCommandTargets?: IResolvable | Array<cloudwatchEventTarget.CloudwatchEventTargetRunCommandTargets>;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/cloudwatch_event_target#role_arn CloudwatchEventTarget#role_arn}.
   * @stability stable
   */
  readonly roleArn?: string;
  /**
   * retry_policy block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/cloudwatch_event_target#retry_policy CloudwatchEventTarget#retry_policy}
   * @stability stable
   */
  readonly retryPolicy?: cloudwatchEventTarget.CloudwatchEventTargetRetryPolicy;
  /**
   * redshift_target block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/cloudwatch_event_target#redshift_target CloudwatchEventTarget#redshift_target}
   * @stability stable
   */
  readonly redshiftTarget?: cloudwatchEventTarget.CloudwatchEventTargetRedshiftTarget;
  /**
   * kinesis_target block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/cloudwatch_event_target#kinesis_target CloudwatchEventTarget#kinesis_target}
   * @stability stable
   */
  readonly kinesisTarget?: cloudwatchEventTarget.CloudwatchEventTargetKinesisTarget;
  /**
   * http_target block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/cloudwatch_event_target#http_target CloudwatchEventTarget#http_target}
   * @stability stable
   */
  readonly httpTarget?: cloudwatchEventTarget.CloudwatchEventTargetHttpTarget;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/cloudwatch_event_target#force_destroy CloudwatchEventTarget#force_destroy}.
   * @stability stable
   */
  readonly forceDestroy?: boolean | IResolvable;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/cloudwatch_event_target#event_bus_name CloudwatchEventTarget#event_bus_name}.
   * @stability stable
   */
  readonly eventBusName?: string;
  /**
   * ecs_target block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/cloudwatch_event_target#ecs_target CloudwatchEventTarget#ecs_target}
   * @stability stable
   */
  readonly ecsTarget?: cloudwatchEventTarget.CloudwatchEventTargetEcsTarget;
  /**
   * dead_letter_config block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/cloudwatch_event_target#dead_letter_config CloudwatchEventTarget#dead_letter_config}
   * @stability stable
   */
  readonly deadLetterConfig?: cloudwatchEventTarget.CloudwatchEventTargetDeadLetterConfig;
  /**
   * batch_target block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/cloudwatch_event_target#batch_target CloudwatchEventTarget#batch_target}
   * @stability stable
   */
  readonly batchTarget?: cloudwatchEventTarget.CloudwatchEventTargetBatchTarget;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/cloudwatch_event_target#arn CloudwatchEventTarget#arn}.
   * @stability stable
   */
  readonly arn: string;
  /**
   * @stability experimental
   */
  readonly provisioners?: Array<FileProvisioner | LocalExecProvisioner | RemoteExecProvisioner>;
  /**
   * @stability experimental
   */
  readonly lifecycle?: TerraformResourceLifecycle;
  /**
   * @stability experimental
   */
  readonly forEach?: ITerraformIterator;
  /**
   * @stability experimental
   */
  readonly dependsOn?: Array<ITerraformDependable>;
  /**
   * @stability experimental
   */
  readonly count?: number | TerraformCount;
  /**
   * @stability experimental
   */
  readonly connection?: SSHProvisionerConnection | WinrmProvisionerConnection;
}
