// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import type { FileProvisioner, IResolvable, ITerraformDependable, ITerraformIterator, LocalExecProvisioner, RemoteExecProvisioner, SSHProvisionerConnection, TerraformCount, TerraformProvider, TerraformResourceLifecycle, WinrmProvisionerConnection } from 'cdktf';
import type { lambdaEventSourceMapping } from '@cdktf/provider-aws';

/**
 * Provides a Lambda event source mapping..
 * This allows Lambda functions to get events from Kinesis, DynamoDB, SQS, Amazon MQ and Managed Streaming for Apache Kafka (MSK)
 * For information about event source mappings, see
 * [CreateEventSourceMapping](http://docs.aws.amazon.com/lambda/latest/dg/API_CreateEventSourceMapping.html) in the API docs.
 */
export interface EventSourceMappingConfig {
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#tumbling_window_in_seconds LambdaEventSourceMapping#tumbling_window_in_seconds}.
   * @stability stable
   */
  readonly tumblingWindowInSeconds?: number;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#topics LambdaEventSourceMapping#topics}.
   * @stability stable
   */
  readonly topics?: Array<string>;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#starting_position_timestamp LambdaEventSourceMapping#starting_position_timestamp}.
   * @stability stable
   */
  readonly startingPositionTimestamp?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#starting_position LambdaEventSourceMapping#starting_position}.
   * @stability stable
   */
  readonly startingPosition?: string;
  /**
   * source_access_configuration block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#source_access_configuration LambdaEventSourceMapping#source_access_configuration}
   * @stability stable
   */
  readonly sourceAccessConfiguration?: IResolvable | Array<lambdaEventSourceMapping.LambdaEventSourceMappingSourceAccessConfiguration>;
  /**
   * self_managed_kafka_event_source_config block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#self_managed_kafka_event_source_config LambdaEventSourceMapping#self_managed_kafka_event_source_config}
   * @stability stable
   */
  readonly selfManagedKafkaEventSourceConfig?: lambdaEventSourceMapping.LambdaEventSourceMappingSelfManagedKafkaEventSourceConfig;
  /**
   * self_managed_event_source block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#self_managed_event_source LambdaEventSourceMapping#self_managed_event_source}
   * @stability stable
   */
  readonly selfManagedEventSource?: lambdaEventSourceMapping.LambdaEventSourceMappingSelfManagedEventSource;
  /**
   * scaling_config block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#scaling_config LambdaEventSourceMapping#scaling_config}
   * @stability stable
   */
  readonly scalingConfig?: lambdaEventSourceMapping.LambdaEventSourceMappingScalingConfig;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#queues LambdaEventSourceMapping#queues}.
   * @stability stable
   */
  readonly queues?: Array<string>;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#parallelization_factor LambdaEventSourceMapping#parallelization_factor}.
   * @stability stable
   */
  readonly parallelizationFactor?: number;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#maximum_retry_attempts LambdaEventSourceMapping#maximum_retry_attempts}.
   * @stability stable
   */
  readonly maximumRetryAttempts?: number;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#maximum_record_age_in_seconds LambdaEventSourceMapping#maximum_record_age_in_seconds}.
   * @stability stable
   */
  readonly maximumRecordAgeInSeconds?: number;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#maximum_batching_window_in_seconds LambdaEventSourceMapping#maximum_batching_window_in_seconds}.
   * @stability stable
   */
  readonly maximumBatchingWindowInSeconds?: number;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#kms_key_arn LambdaEventSourceMapping#kms_key_arn}.
   * @stability stable
   */
  readonly kmsKeyArn?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#function_response_types LambdaEventSourceMapping#function_response_types}.
   * @stability stable
   */
  readonly functionResponseTypes?: Array<string>;
  /**
   * filter_criteria block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#filter_criteria LambdaEventSourceMapping#filter_criteria}
   * @stability stable
   */
  readonly filterCriteria?: lambdaEventSourceMapping.LambdaEventSourceMappingFilterCriteria;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#event_source_arn LambdaEventSourceMapping#event_source_arn}.
   * @stability stable
   */
  readonly eventSourceArn?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#enabled LambdaEventSourceMapping#enabled}.
   * @stability stable
   */
  readonly enabled?: boolean | IResolvable;
  /**
   * document_db_event_source_config block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#document_db_event_source_config LambdaEventSourceMapping#document_db_event_source_config}
   * @stability stable
   */
  readonly documentDbEventSourceConfig?: lambdaEventSourceMapping.LambdaEventSourceMappingDocumentDbEventSourceConfig;
  /**
   * destination_config block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#destination_config LambdaEventSourceMapping#destination_config}
   * @stability stable
   */
  readonly destinationConfig?: lambdaEventSourceMapping.LambdaEventSourceMappingDestinationConfig;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#bisect_batch_on_function_error LambdaEventSourceMapping#bisect_batch_on_function_error}.
   * @stability stable
   */
  readonly bisectBatchOnFunctionError?: boolean | IResolvable;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#batch_size LambdaEventSourceMapping#batch_size}.
   * @stability stable
   */
  readonly batchSize?: number;
  /**
   * amazon_managed_kafka_event_source_config block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.68.0/docs/resources/lambda_event_source_mapping#amazon_managed_kafka_event_source_config LambdaEventSourceMapping#amazon_managed_kafka_event_source_config}
   * @stability stable
   */
  readonly amazonManagedKafkaEventSourceConfig?: lambdaEventSourceMapping.LambdaEventSourceMappingAmazonManagedKafkaEventSourceConfig;
  /**
   * @stability experimental
   */
  readonly provisioners?: Array<FileProvisioner | LocalExecProvisioner | RemoteExecProvisioner>;
  /**
   * @stability experimental
   */
  readonly provider?: TerraformProvider;
  /**
   * @stability experimental
   */
  readonly lifecycle?: TerraformResourceLifecycle;
  /**
   * @stability experimental
   */
  readonly forEach?: ITerraformIterator;
  /**
   * @stability experimental
   */
  readonly dependsOn?: Array<ITerraformDependable>;
  /**
   * @stability experimental
   */
  readonly count?: number | TerraformCount;
  /**
   * @stability experimental
   */
  readonly connection?: SSHProvisionerConnection | WinrmProvisionerConnection;
}
