export * from "./event-source-filter";
export * from "./event-source-mapping";
export * from "./event-invoke-config";
export * from "./function-base";
export * from "./function";
export * from "./function-alias";
export * from "./function-destination";
export * from "./function-nodejs";
export * from "./function-permission";
export * from "./function-url";
export * from "./architecture";

export * as sources from "./event-sources";
export * as destinations from "./function-destinations";

// generated by JSII Struct builder to please JSII pacman
export * from "./function-vpc-config.generated";
