// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import type { FileProvisioner, ITerraformDependable, ITerraformIterator, LocalExecProvisioner, RemoteExecProvisioner, SSHProvisionerConnection, TerraformCount, TerraformProvider, TerraformResourceLifecycle, WinrmProvisionerConnection } from 'cdktf';

/**
 * Config for external source (like an EventBridge Rule, SNS, or S3) permission to access the Lambda function
 */
export interface PermissionConfig {
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_permission#statement_id_prefix LambdaPermission#statement_id_prefix}.
   * @stability stable
   */
  readonly statementIdPrefix?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_permission#statement_id LambdaPermission#statement_id}.
   * @stability stable
   */
  readonly statementId?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_permission#source_arn LambdaPermission#source_arn}.
   * @stability stable
   */
  readonly sourceArn?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_permission#source_account LambdaPermission#source_account}.
   * @stability stable
   */
  readonly sourceAccount?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_permission#qualifier LambdaPermission#qualifier}.
   * @stability stable
   */
  readonly qualifier?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_permission#principal_org_id LambdaPermission#principal_org_id}.
   * @stability stable
   */
  readonly principalOrgId?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_permission#id LambdaPermission#id}.
   * Please be aware that the id field is automatically added to all resources in Terraform providers using a Terraform provider SDK version below 2.
   * If you experience problems setting this value it might not be settable. Please take a look at the provider documentation to ensure it should be settable.
   * @stability stable
   */
  readonly id?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_permission#function_url_auth_type LambdaPermission#function_url_auth_type}.
   * @stability stable
   */
  readonly functionUrlAuthType?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_permission#event_source_token LambdaPermission#event_source_token}.
   * @stability stable
   */
  readonly eventSourceToken?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_permission#principal LambdaPermission#principal}.
   * @stability stable
   */
  readonly principal: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_permission#action LambdaPermission#action}.
   * @stability stable
   */
  readonly action: string;
  /**
   * @stability experimental
   */
  readonly provisioners?: Array<FileProvisioner | LocalExecProvisioner | RemoteExecProvisioner>;
  /**
   * @stability experimental
   */
  readonly provider?: TerraformProvider;
  /**
   * @stability experimental
   */
  readonly lifecycle?: TerraformResourceLifecycle;
  /**
   * @stability experimental
   */
  readonly forEach?: ITerraformIterator;
  /**
   * @stability experimental
   */
  readonly dependsOn?: Array<ITerraformDependable>;
  /**
   * @stability experimental
   */
  readonly count?: number | TerraformCount;
  /**
   * @stability experimental
   */
  readonly connection?: SSHProvisionerConnection | WinrmProvisionerConnection;
}
