// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import type { lambdaFunctionUrl } from '@cdktf/provider-aws';
import type { FileProvisioner, ITerraformDependable, ITerraformIterator, LocalExecProvisioner, RemoteExecProvisioner, SSHProvisionerConnection, TerraformCount, TerraformProvider, TerraformResourceLifecycle, WinrmProvisionerConnection } from 'cdktf';

/**
 * Config for Lambda function URL resource. A function URL is a dedicated HTTP(S) endpoint for a Lambda function.
 */
export interface UrlConfig {
  /**
   * timeouts block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_function_url#timeouts LambdaFunctionUrl#timeouts}
   * @stability stable
   */
  readonly timeouts?: lambdaFunctionUrl.LambdaFunctionUrlTimeouts;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_function_url#qualifier LambdaFunctionUrl#qualifier}.
   * @stability stable
   */
  readonly qualifier?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_function_url#invoke_mode LambdaFunctionUrl#invoke_mode}.
   * @stability stable
   */
  readonly invokeMode?: string;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_function_url#id LambdaFunctionUrl#id}.
   * Please be aware that the id field is automatically added to all resources in Terraform providers using a Terraform provider SDK version below 2.
   * If you experience problems setting this value it might not be settable. Please take a look at the provider documentation to ensure it should be settable.
   * @stability stable
   */
  readonly id?: string;
  /**
   * cors block.
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_function_url#cors LambdaFunctionUrl#cors}
   * @stability stable
   */
  readonly cors?: lambdaFunctionUrl.LambdaFunctionUrlCors;
  /**
   * Docs at Terraform Registry: {@link https://registry.terraform.io/providers/hashicorp/aws/5.60.0/docs/resources/lambda_function_url#authorization_type LambdaFunctionUrl#authorization_type}.
   * @stability stable
   */
  readonly authorizationType: string;
  /**
   * @stability experimental
   */
  readonly provisioners?: Array<FileProvisioner | LocalExecProvisioner | RemoteExecProvisioner>;
  /**
   * @stability experimental
   */
  readonly provider?: TerraformProvider;
  /**
   * @stability experimental
   */
  readonly lifecycle?: TerraformResourceLifecycle;
  /**
   * @stability experimental
   */
  readonly forEach?: ITerraformIterator;
  /**
   * @stability experimental
   */
  readonly dependsOn?: Array<ITerraformDependable>;
  /**
   * @stability experimental
   */
  readonly count?: number | TerraformCount;
  /**
   * @stability experimental
   */
  readonly connection?: SSHProvisionerConnection | WinrmProvisionerConnection;
}
